version: '3'
services:
  mysql-customer-service:
    image: "mysql:5.6"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=customers
      - MYSQL_USER=customer
      - MYSQL_PASSWORD=customer
    volumes:
      - data-mysql-customer:/var/lib/mysql
  mysql-order-service:
    image: "mysql:5.6"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=orders
      - MYSQL_USER=order
      - MYSQL_PASSWORD=order
    volumes:
      - data-mysql-order:/var/lib/mysql
  mysql-product-service:
    image: "mysql:5.6"
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=products
      - MYSQL_USER=product
      - MYSQL_PASSWORD=product
    volumes:
      - data-mysql-product:/var/lib/mysql
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-home:/usr/share/grafana
      - grafana-data:/var/lib/grafana
      - grafana-plugins:/var/lib/grafana/plugins
      - grafana-provisioning:/etc/grafana/provisioning
volumes:
  data-mysql-customer:
  data-mysql-order:
  data-mysql-product:
  grafana-home:
  grafana-data:
  grafana-plugins:
  grafana-provisioning:
  prometheus-data:
